### ISSUE TITLE
Still getting: #<NoMethodError: undefined method `[]' for nil:NilClass>

### ISSUE THREAD

**Issue by Hoyle** [r509/r509-ca-http#36]
Ok, I'm new to this, so it's probably something I did... sorry. I followed the "How To" from Langui.sh (https://langui.sh/2012/11/02/building-a-ca-r509-howto/ - Thanks!), but I'm getting this error:

NoMethodError: undefined method `[]' for nil:NilClass

And I'm getting it even thought I updated the config.ru file as was suggested in issue #33. Has anyone else had this problem? Anyone have any ideas?

Thanks.

Eric

**Comment by reaperhulk** [comment]
Could you post the whole stack trace? Usually this is an issue with the yaml rather than the config.ru (which should look like https://github.com/r509/r509-ca-http/blob/master/config.ru)

**Comment by Hoyle** [comment]
Thanks for your help! I apologize for the dump below, but I wasn't sure what you needed. I will look at the Yaml file tonight.

I, [2015-07-13T22:47:11.106800 #1103]  INFO -- : Issue Certificate
I, [2015-07-13T22:47:11.106868 #1103]  INFO -- : ca=r509_howto_ca&profile=server&validityPeriod=31536000&subject%5BC%5D=US&subject%5BST%5D=&subject%5BL%5D=&subject%5BO%5D=&subject%5BOU%5D=&subject%5BCN%5D=&subject%5BemailAddress%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&csr=-----BEGIN+CERTIFICATE+REQUEST-----%0D%0AMIIClTCCAX0CAQAwUDELMAkGA1UEBhMCVVMxETAPBgNVBAgMCElsbGlub2lzMRAw%0D%0ADgYDVQQHDAdDaGljYWdvMREwDwYDVQQKDAhyNTA5IExMQzEJMAcGA1UEAwwAMIIB%0D%0AIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1hs5C6%2BSWIU%2FPUZQYpGj0Hpl%0D%0Ap4RPtuvImY%2BnGx9nVeMehUXpC63XRcssTVsL%2Bek%2BF539rnugN594NxH4Pu2W2Dgv%0D%0Ay5jU%2FDeO18%2FkT6XzLKzQhRIE3Ov6Brf3M292JBELgCi3fwbdQcNRCWMQehl6Hmz7%0D%0AjhZYB1QEeYWAPG5Ei76c68ktpe8qYiCsYUcT%2FcECA%2FVeo2fYhac9VF6QdRgOI0bP%0D%0A5GYu8YXqviYlziHuVpx0wdXbAuhXBf7lpSpoz2%2FZpAQq4AXrBm2Pj4G1%2Bq%2BmxgmP%0D%0A1wMYqfHO%2F%2Fik%2F1K9F1CoY0UyX7t3iL4I5yarbU7HSoqk3PAJ6wUKQzVftusnywID%0D%0AAQABoAAwDQYJKoZIhvcNAQEFBQADggEBAAG2nfmBKeOaqnmTcYwScrV22aCjvibl%0D%0AkBXpT60LN0%2BfK4YDpVUPrGlc%2BJ2TEFhHpWSSf%2FXtFRITQgmqZOeafqVvVJZmHtTt%0D%0A94ZOkteX%2Fcm%2F70%2FQo7iZ8s5QGI3vCIOEdqs%2FjrFAUD%2FmXiKiSnzHKF0hrpYrCOU3%0D%0Au7HmTKQVNn1rvM4yA9C55ZEEwTGhIdDg7tt5Klgbdnf0XS8suJQa%2FwgOv79f6Y1%2F%0D%0ATeqoCYaTdvjdftcpgAccWJRrzKiEDJJnEB1D1%2FvzKexHndMfMCsbJyhqscvFBbwz%0D%0AE%2Fs64%2FoE2DOE22YXHm2mxUBQkcODsCEc1lVEqKEreMYgKVQeptKJWQg%3D%0D%0A-----END+CERTIFICATE+REQUEST-----
I, [2015-07-13T22:47:11.107861 #1103]  INFO -- : {"ca"=>"r509_howto_ca", "profile"=>"server", "validityPeriod"=>"31536000", "subject"=>{"C"=>"US", "ST"=>"", "L"=>"", "O"=>"", "OU"=>"", "CN"=>"", "emailAddress"=>""}, "extensions"=>{"subjectAlternativeName"=>["", "", "", "", ""]}, "csr"=>"-----BEGIN CERTIFICATE REQUEST-----\r\nMIIClTCCAX0CAQAwUDELMAkGA1UEBhMCVVMxETAPBgNVBAgMCElsbGlub2lzMRAw\r\nDgYDVQQHDAdDaGljYWdvMREwDwYDVQQKDAhyNTA5IExMQzEJMAcGA1UEAwwAMIIB\r\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1hs5C6+SWIU/PUZQYpGj0Hpl\r\np4RPtuvImY+nGx9nVeMehUXpC63XRcssTVsL+ek+F539rnugN594NxH4Pu2W2Dgv\r\ny5jU/DeO18/kT6XzLKzQhRIE3Ov6Brf3M292JBELgCi3fwbdQcNRCWMQehl6Hmz7\r\njhZYB1QEeYWAPG5Ei76c68ktpe8qYiCsYUcT/cECA/Veo2fYhac9VF6QdRgOI0bP\r\n5GYu8YXqviYlziHuVpx0wdXbAuhXBf7lpSpoz2/ZpAQq4AXrBm2Pj4G1+q+mxgmP\r\n1wMYqfHO//ik/1K9F1CoY0UyX7t3iL4I5yarbU7HSoqk3PAJ6wUKQzVftusnywID\r\nAQABoAAwDQYJKoZIhvcNAQEFBQADggEBAAG2nfmBKeOaqnmTcYwScrV22aCjvibl\r\nkBXpT60LN0+fK4YDpVUPrGlc+J2TEFhHpWSSf/XtFRITQgmqZOeafqVvVJZmHtTt\r\n94ZOkteX/cm/70/Qo7iZ8s5QGI3vCIOEdqs/jrFAUD/mXiKiSnzHKF0hrpYrCOU3\r\nu7HmTKQVNn1rvM4yA9C55ZEEwTGhIdDg7tt5Klgbdnf0XS8suJQa/wgOv79f6Y1/\r\nTeqoCYaTdvjdftcpgAccWJRrzKiEDJJnEB1D1/vzKexHndMfMCsbJyhqscvFBbwz\r\nE/s64/oE2DOE22YXHm2mxUBQkcODsCEc1lVEqKEreMYgKVQeptKJWQg=\r\n-----END CERTIFICATE REQUEST-----"}
2015-07-13 22:47:11 - NoMethodError - undefined method `[]' for nil:NilClass:
/Users/.rvm/gems/ruby-2.2.1/gems/r509-ca-http-0.3.2/lib/r509/certificateauthority/http/server.rb:47:in`ca'
/Users/.rvm/gems/ruby-2.2.1/gems/r509-ca-http-0.3.2/lib/r509/certificateauthority/http/server.rb:114:in `block in <class:Server>'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`[]'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in`route_eval'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in`block in process_route'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in`process_route'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in`each'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in`block in dispatch!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`catch'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in`dispatch!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`block in invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/nulllogger.rb:9:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/head.rb:13:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in`synchronize'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/r509-middleware-certwriter-0.2.1/lib/r509/middleware/certwriter.rb:20:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/r509-middleware-validity-0.2.1/lib/r509/middleware/validity.rb:20:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/tempfile_reaper.rb:15:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/lint.rb:49:in `_call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/lint.rb:37:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/chunked.rb:54:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/content_length.rb:15:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in`service'
/Users/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/Users/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in`run'
/Users/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
E, [2015-07-13T22:47:11.109486 #1103] ERROR -- : #<NoMethodError: undefined method`[]' for nil:NilClass>
E, [2015-07-13T22:47:11.109558 #1103] ERROR -- : /Users/.rvm/gems/ruby-2.2.1/gems/r509-ca-http-0.3.2/lib/r509/certificateauthority/http/server.rb:47:in `ca'
/Users/.rvm/gems/ruby-2.2.1/gems/r509-ca-http-0.3.2/lib/r509/certificateauthority/http/server.rb:114:in`block in class:Server'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in`block in compile!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`block (3 levels) in route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in`block (2 levels) in route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in`catch'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in`block in route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in`route!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`block in invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in`block in call!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in`catch'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in`call!'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/nulllogger.rb:9:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/head.rb:13:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`block in call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/r509-middleware-certwriter-0.2.1/lib/r509/middleware/certwriter.rb:20:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/r509-middleware-validity-0.2.1/lib/r509/middleware/validity.rb:20:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/lint.rb:49:in`_call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/lint.rb:37:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/showexceptions.rb:24:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/commonlogger.rb:33:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/chunked.rb:54:in `call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/content_length.rb:15:in`call'
/Users/.rvm/gems/ruby-2.2.1/gems/rack-1.6.1/lib/rack/handler/webrick.rb:89:in `service'
/Users/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in`service'
/Users/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/Users/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in`block in start_thread'
::1 - - [13/Jul/2015:22:47:11 -0400] "POST /1/certificate/issue/ HTTP/1.1" 500 56 0.0049
D, [2015-07-13T22:47:11.175210 #1103] DEBUG -- : go away. no children.
::1 - - [13/Jul/2015:22:47:11 -0400] "GET /favicon.ico HTTP/1.1" 200 20 0.0006

**Comment by Hoyle** [comment]
Fixed! It was the yaml file. Sorry for the delay in posting and thanks for your help.
